# Generated by Django 6.0 on 2026-01-02 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id_artista', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_nacimiento', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('mega', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Compañias',
            fields=[
                ('id_compañia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Artista_Nombres',
            fields=[
                ('id_relacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.artista')),
            ],
        ),
        migrations.AddField(
            model_name='artista',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.ciudad'),
        ),
        migrations.CreateModel(
            name='Artista_Compañias',
            fields=[
                ('id_relacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.artista')),
                ('compañia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.compañias')),
            ],
        ),
        migrations.AddField(
            model_name='artista',
            name='compañia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.compañias'),
        ),
        migrations.CreateModel(
            name='Artistas_Generos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.artista')),
                ('genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('GG', 'Girl Groups'), ('BAND', 'Bandas')], max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_fandom', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_debut', models.DateField()),
                ('mega', models.CharField(max_length=100)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.ciudad')),
                ('compañia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.compañias')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Artista_Grupos',
            fields=[
                ('id_relacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.artista')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.grupos')),
            ],
        ),
        migrations.CreateModel(
            name='Grupos_Compañias',
            fields=[
                ('id_relacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('compañia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.compañias')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.grupos')),
            ],
        ),
        migrations.CreateModel(
            name='Grupos_Generos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.genero')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.grupos')),
            ],
        ),
        migrations.CreateModel(
            name='Grupos_Nombres',
            fields=[
                ('id_relacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.grupos')),
            ],
        ),
        migrations.AddField(
            model_name='ciudad',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.pais'),
        ),
        migrations.AddField(
            model_name='artista',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.pais'),
        ),
        migrations.CreateModel(
            name='Secciones',
            fields=[
                ('id_seccion', models.AutoField(primary_key=True, serialize=False)),
                ('orden', models.IntegerField()),
                ('titulo', models.CharField(max_length=100)),
                ('id_seccion_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.secciones')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id_video', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('youtube', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('artista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.artista')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.grupos')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.secciones')),
            ],
        ),
    ]
