# Generated by Django 6.0 on 2026-01-03 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artista',
            options={'verbose_name': 'Artista', 'verbose_name_plural': 'Artistas'},
        ),
        migrations.AlterModelOptions(
            name='artista_compañias',
            options={'verbose_name': 'Artista_Compañias', 'verbose_name_plural': 'Artista_Compañias'},
        ),
        migrations.AlterModelOptions(
            name='artista_grupos',
            options={'verbose_name': 'Artista_Grupos', 'verbose_name_plural': 'Artista_Grupos'},
        ),
        migrations.AlterModelOptions(
            name='artista_nombres',
            options={'verbose_name': 'Artista_Nombres', 'verbose_name_plural': 'Artista_Nombres'},
        ),
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='compañias',
            options={'verbose_name': 'Compañía', 'verbose_name_plural': 'Compañías'},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'verbose_name': 'Género', 'verbose_name_plural': 'Géneros'},
        ),
        migrations.AlterModelOptions(
            name='grupos',
            options={'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
        migrations.AlterModelOptions(
            name='grupos_compañias',
            options={'verbose_name': 'Grupos_Compañias', 'verbose_name_plural': 'Grupos_Compañias'},
        ),
        migrations.AlterModelOptions(
            name='grupos_nombres',
            options={'verbose_name': 'Grupos_Nombres', 'verbose_name_plural': 'Grupos_Nombres'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
        migrations.AlterModelOptions(
            name='secciones',
            options={'verbose_name': 'Sección', 'verbose_name_plural': 'Secciones'},
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.RemoveField(
            model_name='videos',
            name='artista',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='grupo',
        ),
        migrations.AlterField(
            model_name='grupos',
            name='tipo',
            field=models.CharField(choices=[('GG', 'Girl Group'), ('BAND', 'Bandas')], max_length=10),
        ),
        migrations.CreateModel(
            name='Videos_Artistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.artista')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.videos')),
            ],
            options={
                'verbose_name': 'Videos_Artistas',
                'verbose_name_plural': 'Videos_Artistas',
            },
        ),
        migrations.CreateModel(
            name='Videos_Grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.grupos')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.videos')),
            ],
            options={
                'verbose_name': 'Videos_Grupos',
                'verbose_name_plural': 'Videos_Grupos',
            },
        ),
    ]
