# Generated by Django 6.0 on 2026-01-18 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_alter_artista_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artistas_generos',
            options={'verbose_name': 'Artistas_Generos', 'verbose_name_plural': 'Artistas_Generos'},
        ),
        migrations.AlterModelOptions(
            name='grupos_generos',
            options={'verbose_name': 'Grupos_Generos', 'verbose_name_plural': 'Grupos_Generos'},
        ),
        migrations.RemoveField(
            model_name='grupos',
            name='ciudad',
        ),
    ]
